service: jira
type: Create jira ticket
image: dotenx/task-and-trigger:create-jira-ticket-lambda5
integrations: [jira]
has_dynamic_variables: false
fields:
    - key: project_key
      type: text
    - key: issue_type
      type: text
    - key: description
      type: text
    - key: summery
      type: text
    - key: jira_url
      type: text
author: Armingodiz
icon: https://cdn-icons-png.flaticon.com/512/5968/5968875.png
node_color: 5364AD
description: Creates a jira issue with given detailes
