service: google
type: Google send email
image: dotenx/task-and-trigger:google-send-email-lambda4
integrations: [google]
fields:
    - key: from
      type: text
      description: your email address (e.g abc@gmail.com)
    - key: to
      type: text
      description: destination email address (e.g abc@example.com)
    - key: subject
      type: text
      description: subject of email
    - key: message
      type: text
      description: text/message of email
author: Hojjat-1
icon: https://cdn-icons-png.flaticon.com/512/281/281764.png
node_color: FBFB11
description: Send an email message with gmail service
