service: facebook
type: Publish post
image: dotenx/task-and-trigger:facebook-publish-post-lambda4
integrations: [facebook]
fields:
    - key: page_id
      type: text
      description: id of Facebook page
    - key: text
      type: text
      description: text that you want to share on a post
author: Hojjat-1
icon: https://cdn-icons-png.flaticon.com/512/124/124010.png
node_color: 3b5998
description: Publish a post on specific page
