service: discord
type: Send discord message
image: dotenx/task-and-trigger:send-discord-message-lambda4
fields:
    - key: TEXT
      type: text
      display_name: text
    - key: WEBHOOK_URL
      type: text
      display_name: webhook url
author: hawwwdi
icon: https://www.svgrepo.com/show/353655/discord-icon.svg
node_color: 5865F2
description: Sends discord message using discord channel webhook
