service: hubspot
type: Create new contact
image: dotenx/task-and-trigger:hubspot-create-contact-lambda
integrations: [hubspot]
fields:
    - key: properties
      type: object
      display_name: Properties
      description: A json format field that keys are property names and value of each key is the value that you want to set for that property
author: Hojjat-1
icon: https://seeklogo.com/images/H/hubspot-logo-A06A6E0DF5-seeklogo.com.png
node_color: FF6442
description: Creates a contact on your HubSpot account
