service: twitter
type: Send tweet
image: dotenx/task-and-trigger:twitter-send-tweet-lambda5
integrations: [twitter]
fields:
    - key: text
      type: text
      description: text of tweet that will share
author: Hojjat-1
icon: https://cdn-icons-png.flaticon.com/512/3128/3128310.png
node_color: 00acee
description: Sends a tweet with user's access token, access token secret, ... (oauth1.0a)
