service: stripe
type: Stripe update customer
image: dotenx/task-and-trigger:stripe-update-customer-lambda5
integrations: [stripe]
fields:
    - key: CUS_NAME
      type: text
      description: customer's name (e.g hadi)
      display_name: customer name
    - key: CUS_PHONE
      type: text
      description: customer's phone number (e.g +989123737689)
      display_name: customer phone
    - key: CUS_EMAIL
      type: text
      description: customer's email address (e.g abc@gmail.com)
      display_name: customer email
    - key: CUS_ID
      type: text
      description: customer's stripe Id (e.g cus_sadfa8234sad)
      display_name: customer id
author: hawwwdi
icon: https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg
node_color: 665BFF
description: update an exesiting customer
