service: database
type: Update a table record
image: dotenx/task-and-trigger:database-update-record-lambda6
fields:
    - key: dtx_access_token
      type: text
      display_name: DoTenX access token
      description: Your DoTenX personal access token
    - key: project_tag
      type: text
      display_name: Project tag 
      description: Your DoTenX project tag
    - key: table_name
      type: text
      display_name: Table name 
      description: Your DoTenX table name
    - key: row_id
      type: text
      display_name: Row id
      description: The id of record that you want update it
    - key: column_values
      type: object
      display_name: Column values
      description: A json format field that keys are column names and values are record values
author: Hojjat-1
icon: https://cdn-icons-png.flaticon.com/512/138/138932.png
node_color: 4ABAFF
description: Update a record of your DoTenX table

